name: my_tribe
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  cached_network_image: ^3.2.0
  connectivity_plus: ^2.2.1
  device_info_plus: ^3.2.2
  email_validator: ^2.0.1
  flutter_multi_formatter: ^2.5.1
  flutter_screenutil: ^5.3.1
  flutter_secure_storage: ^5.0.2
  flutter_staggered_grid_view: ^0.6.1
  fluttericon: ^2.0.0
  fluttertoast: ^8.0.9
  get: ^4.6.1
  google_fonts: ^2.3.1
  intl: ^0.17.0
  internet_connection_checker: ^0.0.1+3


  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^1.0.4
  logger: ^1.1.0

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/
